all: chx2html.xsl chf2html.xsl

chx2html.xsl:
    xsllint -xinclude chx2html.src.xsl > chx2html.xsl

chf2html.xsl:
    xsllint -xinclude chf2html.src.xsl > chf2html.xsl

clean:

distclean:

realclean:
    rm chx2html.xsl
    rm chf2html.xsl
