#! /usr/bin/python


import dbus
import dbus.mainloop
import dbus.mainloop.glib

import gobject


def receiver(barcodestring,typestring):
    #print "receiver: *args=%s **kwargs=%s" % (str(args),str(kwargs))
    print "barcodestring=%s" % (barcodestring)
    pass


dbusname="edu.iastate.cnde.thermal.BarcodeReader"
dbuspath="/edu/iastate/cnde/thermal/barcode"

dbusloop=dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
loop=gobject.MainLoop()

#system_bus = dbus.SystemBus(mainloop=dbusloop)
system_bus = dbus.SystemBus()


signal_name="read"
dbus_interface=dbusname # "edu.iastate.cnde.thermal.BarcodeReader" 
bus_name=None  #??? 
path=dbuspath # "/edu/iastate/cnde/thermal/barcode"

SignalMatch=system_bus.add_signal_receiver(receiver,signal_name,dbus_interface,bus_name,path)
#  can add these additional keyword parameters to add_signal_recevier: sender_keyword="sender",destination_keyword="destination",interface_keyword="interface",member_keyword="member",path_keyword="path")

loop.run()
